print("CALCULADORA")
print("Introduzca dos números:")
n1 = int(input())
n2 = int(input())
print("Suma: " + str(n1) + " + " + str(n2) + " =", n1+n2)
print("Resta: " + str(n1) + " - " + str(n2) + " =", n1-n2)
print("Multiplicación: " + str(n1) + " x " + str(n2) + " =", n1*n2)
print("División: " + str(n1) + " / " + str(n2) + " =", n1/n2)
print("Resto: " + str(n1) + " % " + str(n2) + " =", n1%n2)